version: "3.8"
services:
  aidadsp:
    image: aidadsp/pytorch:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aidadsp
    working_dir: /content/Automated-GuitarAmpModelling
    environment:
      - 'JUPYTER_TOKEN=aidadsp'
    volumes:
      - ./:/content/Automated-GuitarAmpModelling
    ports:
      - 8080:8888
      - 6006:6006
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
